### ISSUE TITLE
What exactly is this?

### ISSUE THREAD

**Issue by martinerk0** [khoih-prog/LittleFS_Mbed_RP2040#5]
Hello what does this mean?

` char fileName[] = MBED_LITTLEFS_FILE_PREFIX "/counts.txt";`

Is that C++ or C code? I mean you are constructing array of chars from define which is itself array of chars as here:

` #define MBED_LITTLEFS_FILE_NAME     "littlefs"
  #define MBED_LITTLEFS_FILE_PREFIX   "/" MBED_LITTLEFS_FILE_NAME`

and then you are using that path inside functions such as:

`void writeFile(const char * path, const char * message, size_t messageSize) `

which are pointers to chars... this is C right?

**Comment by khoih-prog** [comment]
Sorry I don't have time to answer these types of questions.
You'd better do the research yourself or ask question on some Forums.
